version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: songs-microservice-sqlserver-1
    ports:
      - "1434:1433"          # Host 1434 → Cont. 1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!   # ← Agregué “!” al final
      - MSSQL_PID=Express
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network
    restart: unless-stopped

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_USERNAME=usr_polimusic_gr2
      - DB_PASSWORD=Politecnica1
      - DB_NAME=BDD_PoliMusic_Song
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - sqlserver
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data:
